# Generated by Django 5.2.6 on 2025-09-09 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('gear', 'Gear'), ('gloves', 'Gloves'), ('merch', 'Merch'), ('bag', 'Bag'), ('sock', 'Sock'), ('shorts', 'Shorts'), ('hoodie', 'Hoodie'), ('cap', 'Cap'), ('bottle', 'Bottle'), ('net', 'Net'), ('cone', 'Cone')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
