# Generated by Django 5.2.6 on 2025-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('gear', 'Gear'), ('gloves', 'Gloves'), ('merch', 'Merch'), ('bag', 'Bag'), ('sock', 'Sock'), ('shorts', 'Shorts'), ('hoodie', 'Hoodie'), ('cap', 'Cap'), ('bottle', 'Bottle'), ('net', 'Net'), ('cone', 'Cone')], max_length=20),
        ),
    ]
